<?php

/**
 * BaseEmailPackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idemailpackage
 * @property string $recipient
 * @property string $address
 * @property integer $email_id
 * @property Email $Email
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmailPackage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('email_package');
        $this->hasColumn('idemailpackage', 'integer', null, array(
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('recipient', 'string', null, array(
             'notnull' => false,
             'type' => 'string',
             ));
        $this->hasColumn('address', 'string', null, array(
             'notnull' => false,
             'type' => 'string',
             ));
        $this->hasColumn('email_id', 'integer', null, array(
             'unsigned' => true,
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Email', array(
             'local' => 'email_id',
             'foreign' => 'idemails'));
    }
}