<?php

/**
 * BaseAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idaddress
 * @property string $city
 * @property string $zipCode
 * @property string $street
 * @property tinyint $billing
 * @property tinyint $shipping
 * @property integer $client_id
 * @property Client $Client
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAddress extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('addresses');
        $this->hasColumn('idaddress', 'integer', null, array(
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('zipCode', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));
        $this->hasColumn('street', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('billing', 'tinyint', 1, array(
             'type' => 'tinyint',
             'length' => '1',
             ));
        $this->hasColumn('shipping', 'tinyint', 1, array(
             'type' => 'tinyint',
             'length' => '1',
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'unsigned' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'idclients'));
    }
}