<?php

/**
 * BaseExpCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idexpcategories
 * @property string $name
 * @property Doctrine_Collection $Expense
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('expcategories');
        $this->hasColumn('idexpcategories', 'integer', null, array(
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Expense', array(
             'local' => 'idexpcategories',
             'foreign' => 'expcategory_id'));
    }
}