<?php

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idclients
 * @property string $name
 * @property string $lastName
 * @property string $tel
 * @property string $email
 * @property string $www
 * @property string $note
 * @property tinyint $target
 * @property Doctrine_Collection $Address
 * @property Doctrine_Collection $Order
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('clients');
        $this->hasColumn('idclients', 'integer', null, array(
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('lastName', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('tel', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('www', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('target', 'tinyint', 1, array(
             'type' => 'tinyint',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Address', array(
             'local' => 'idclients',
             'foreign' => 'client_id'));

        $this->hasMany('Order', array(
             'local' => 'idclients',
             'foreign' => 'client_id'));
    }
}