<?php

/**
 * EmailPackageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailPackageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailPackageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailPackage');
    }
}